FROM quay.agilesof.com/brandi/brandi-python-ubi:v0.0.4

LABEL name="Flask + Graphene Project" maintainer="Mitchell Murphy<mitchell.murphy@spathesystems.com>"

ARG APP_ROOT=/usr/src/app

# set work directory
WORKDIR ${APP_ROOT}

USER root
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY Pipfile* .
RUN pipenv install --system --deploy

USER 1001
COPY . .

EXPOSE 8080

CMD gunicorn --bind 0.0.0.0:8080 wsgi
